package com.project.thermallogistics.model.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@Schema(description = "Auto-generated installation and teardown schedule for an Ice Project")
public class InstallationSchedule {

    @Schema(description = "Project identifier")
    private Long projectId;

    @Schema(description = "Project name")
    private String projectName;

    @Schema(description = "Recommended arrival and preparation time")
    private LocalDateTime setupArrivalTime;

    @Schema(description = "Recommended sculpture installation start time")
    private LocalDateTime recommendedInstallationTime;

    @Schema(description = "Start of peak visual clarity window")
    private LocalDateTime peakClarityStart;

    @Schema(description = "End of peak visual clarity window (10% mass loss reached)")
    private LocalDateTime peakClarityEnd;

    @Schema(description = "Estimated time of structural failure under current conditions")
    private LocalDateTime estimatedStructuralFailureTime;

    @Schema(description = "Mandatory teardown deadline (failure time minus safety buffer)")
    private LocalDateTime mandatoryTeardownTime;

    @Schema(description = "Total estimated melt time from installation (hours)")
    private Double estimatedMeltTimeHours;

    @Schema(description = "Peak clarity window duration (hours)")
    private Double peakClarityDurationHours;

    @Schema(description = "Safe display window from installation to teardown (hours)")
    private Double safeDisplayWindowHours;

    @Schema(description = "Ambient temperature used for this schedule (C)")
    private Double forecastTemperatureCelsius;

    @Schema(description = "Effective temperature after all cooling adjustments (C)")
    private Double effectiveTemperatureCelsius;

    @Schema(description = "Whether the event fully fits within the safe display window")
    private Boolean eventFitsInSafeWindow;

    @Schema(description = "Setup lead time in minutes based on sculpture volume")
    private Integer setupLeadTimeMinutes;

    @Schema(description = "Operational recommendations generated by the scheduler")
    private List<String> recommendations;

    @Schema(description = "Weather summary for the event period")
    private String weatherSummary;

    @Schema(description = "Schedule generated at")
    private LocalDateTime generatedAt;
}
